=== chlin501/treenee/tree-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "This is the schema for the Tree structure definition",
  "type": "object",
  "definitions": {
    "nodes": {
      "type": "array",
      "items": {
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "prompt": {
            "type": "string"
          },
          "options": {
            "$ref": "#/definitions/options"
          }
        },
        "additionalProperties": false,
        "required": ["id", "title"]
      }
    },
    "options": {
      "type": "array",
      "items": {
        "properties": {
          "_id": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "nextNodeId": {
            "type": "string"
          },
          "value": {
            "type": "number"
          }
        },
        "additionalProperties": false,
        "required": ["text", "nextNodeId"]
      }
    }
  },
  "properties": {
    "_meta": {
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "accessCode": {
      "type": "string"
    },
    "startNodeId": {
      "description": "Identifier of the first node to show. Defaults to the first in the node list",
      "type": "string"
    },
    "trackVisits": {
      "description": "Wether to detect if a node has already been visited or not. Using 'value' in this case would be pointless. Default true",
      "type": "boolean"
    },
    "nodes": {
      "$ref": "#/definitions/nodes"
    }
  },
  "additionalProperties": false,
  "required": ["name", "title", "nodes"]
}

=== chlin501/treenee/trees/example/tree.json
{
  "name": "An example decision tree",
  "title": "How to select the best programming language",
  "description": "Let me help you selecting the best programming language",
  "accessCode": "",
  "startNodeId": "start",
  "trackVisits": true,
  "nodes": [
    {
      "id": "start",
      "title": "Understanding your needs",
      "body": "This is the <strong>first</strong> question.",
      "prompt": "Is your application mission critical?",
      "options": [
        {
          "text": "Yes it is!",
          "nextNodeId": "mission-critical",
          "value": 0
        },
        {
          "text": "No, it's just a demo",
          "nextNodeId": "demo-application",
          "value": 0
        }
      ]
    },
    {
      "id": "mission-critical",
      "title": "A mission critical application",
      "body": "A mission critical application needs a powerful language!",
      "prompt": "How much power do you need?",
      "options": [
        {
          "text": "From 0 to 10",
          "nextNodeId": "javascript",
          "value": 0
        },
        {
          "text": "From 11 to 100",
          "nextNodeId": "javascript",
          "value": 0
        },
        {
          "text": "More than 100!",
          "nextNodeId": "javascript",
          "value": 0
        }
      ]
    },
    {
      "id": "demo-application",
      "title": "Just a demo application",
      "body": "While building a demo application, we can consider experimenting some new skills.",
      "prompt": "Which skills do you want to learn better?",
      "options": [
        {
          "text": "Functional programming",
          "nextNodeId": "python",
          "value": 0
        },
        {
          "text": "Object oriented programming",
          "nextNodeId": "python",
          "value": 0
        },
        {
          "text": "Magic with cards",
          "nextNodeId": "python",
          "value": 0
        }
      ]
    },
    {
      "id": "javascript",
      "title": "The perfect language is…",
      "body": "The perfect language to use in your case is definitely <strong>JavaScript</strong>."
    },
    {
      "id": "python",
      "title": "The perfect language is…",
      "body": "The perfect language to use in your case is definitely <strong>Python</strong>."
    }
  ]
}
